// Code generated by test DO NOT EDIT.

package skipgen

import "fakesensitive"

// GeneratedStruct is in a generated file.
// With SkipGenerated, this is not flagged.
type GeneratedStruct struct {
	x fakesensitive.String
}
